#!/usr/bin/env node
// -*- mode: js -*-

const fs = require('fs');
const slm = require('slm');

function read(file, encoding) {
	encoding = encoding || 'utf8';
	return new Promise((resolve, reject) => {
		if(typeof file === 'string') {
			fs.readFile(file, encoding, (error, data) => {
				if(error) {
					reject(error);
				}
				else {
					resolve(data);
				}
			});
		}
		else {
			let data = '';
			file.setEncoding(encoding);
			file.on('readable', () => {
				let chunk;
				while((chunk = file.read())) {
					data += chunk;
				}
			});
			file.on('error', (err) => reject(err));
			file.on('end', () => resolve(data));
		}
	});
}

function write(file, data) {
	if(typeof file === 'string') {
		fs.writeFileSync(file, data);
	}
	else {
		file.write(data);
	}
}

function main(options) {
	let data;
	if(options.data) {
		try {
			data = require(options.data);
		}
		catch(e) {
			data = require('./' + options.data);
		}
	}
	else {
		data = {};
	}
	return read(options.input).then((file) => {
		let compiled = slm.compile(file)(data);
		write(options.output, compiled);
	});
}

const program = require('commander')
	.version('0.1.0')
	.option(
		'-i, --input <file>',
		'input slm file (default: stdin)',
		process.stdin
	)
	.option(
		'-o, --output <file>',
		'output html file (default: stdout)',
		process.stdout
	)
	.option(
		'-d, --data <file>',
		'template data module'
	)
	.parse(process.argv);

main(program).catch((err) => {
	console.error(err);
	process.exit(1);
});
